name: Github Actions Demo
on: 
  push:
    branches: 
      - main
    paths-ignore: [.github/**]
  pull_request:
    branches: 
      - main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:

jobs:
  Build:
    name: Build Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Trigger
        run: |
          echo "Event was triggered by ${{ github.event_name }}"
          echo "Reference: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          tree .
    
